project:
  type: website
  output-dir: docs
  resources:
  - shinylive-sw.js
  
website:  
  repo-url: https://github.com/falkcarl/clt
  repo-actions: [edit, issue]
  title: "CLT"

format:
  html:
    grid: 
      body-width: 1400px
      sidebar-width: 200px
      margin-width: 200px

